language: python

python:
  - "3.4"
  - "3.5"
  - "2.7"

env:
  - PIP_USE_MIRRORS=true

install:
  - pip install -U pip setuptools
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install pathlib2; fi
  - pip install -r requirements.txt
  - python setup.py install
  - pip install pandas
  - pip install coveralls

script:
  - python setup.py test
  - coverage run --source=hansel setup.py test

after_success:
  - coveralls
