language: python

matrix:
  include:
  - python: "3.5"
  - python: "3.6"

install:
  - pip install -U pipenv
  - pipenv install --dev
  - pipenv run python setup.py install
  - pipenv run pip install pandas

script:
  - pipenv run flake8 hansel
  - pipenv run pytest -v
  - pipenv run pytest --cov=hansel
  - pipenv run rstcheck README.rst
  - pipenv run rstcheck CHANGES.rst

after_success:
  - pipenv run coveralls
  - pipenv --rm
