language: python

python:
  - "3.6"
  - "3.5"
  - "2.7"

env:
  - PIPENV_VENV_IN_PROJECT=./.venv
  - PIP_USE_MIRRORS=true

install:
  - pip install -U pipenv
  - pipenv install --dev
  - pipenv run python setup.py install
  - pipenv run pip install pandas

script:
  - pipenv run flake8 hansel
  - pipenv run python setup.py test
  - pipenv run coverage run --source=hansel setup.py test

after_success:
  - pipenv run coveralls
  - rm -rf ${PIPENV_VENV_IN_PROJECT}
